// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RFID_tracking_API.Data;

#nullable disable

namespace RFID_tracking_API.Migrations
{
    [DbContext(typeof(RFIDTrackingDbContext))]
    [Migration("20230502084316_Add shooters and directors")]
    partial class Addshootersanddirectors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RFID_tracking_API.Data.Director", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("RFID_tracking_API.Data.Shooter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DirectorAcceptedPictureIdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPictureIdShown")
                        .HasColumnType("bit");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShooterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectorAcceptedPictureIdId");

                    b.ToTable("Shooters");
                });

            modelBuilder.Entity("RFID_tracking_API.Data.Shooter", b =>
                {
                    b.HasOne("RFID_tracking_API.Data.Director", "DirectorAcceptedPictureId")
                        .WithMany()
                        .HasForeignKey("DirectorAcceptedPictureIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirectorAcceptedPictureId");
                });
#pragma warning restore 612, 618
        }
    }
}
